# This application requires a secrets.yaml file formatted as follows.
#   spring:
#       datasource:
#           url: {URL for a mysql database}
#           username: {username for indicated database}
#           password: {password for indicated database}

spring:
    config:
        import: optional:secrets.yaml
    application:
        name: gallery_gavel_jwt_demo
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            jakarta:
                persistence:
                    validation:
                        mode: none
    mvc:
        hiddenmethod:
            filter:
                enabled: true